[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Repositories\abbas-outlook-addin\Setup\out\AbasOutlookAddinSetup.exe
FriendlyName=ABAS Outlook Add-in Setup
AppLaunched=cmd /c install_colleague.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="AbasOutlookAddin.dll"
FILE1="install_colleague.bat"
[SourceFiles]
SourceFiles0=C:\Repositories\abbas-outlook-addin\Setup\iexpress_stage
[SourceFiles0]
%FILE0%=
%FILE1%=